# Generated by Django 4.2.21 on 2025-06-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_created_at_worker_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['full_name'], 'verbose_name': 'Trabajador', 'verbose_name_plural': 'Trabajadores'},
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
    ]
