# Generated by Django 4.2.21 on 2025-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
