# Generated by Django 4.2.21 on 2025-06-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del libro', max_length=2000, null=True),
        ),
    ]
