# Generated by Django 4.2.21 on 2025-06-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_category_alter_book_editorial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editorial',
            new_name='Publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='editorial',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.publisher'),
            preserve_default=False,
        ),
    ]
