# Generated by Django 4.2.21 on 2025-06-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_region_alter_supplier_options_city_supplier_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supply_categories',
            new_name='category',
        ),
    ]
