# Generated by Django 4.2.21 on 2025-06-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_rename_supply_categories_supplier_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
    ]
