# Generated by Django 4.2.21 on 2025-06-03 17:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('individual', 'Persona'), ('company', 'Empresa')], max_length=10, verbose_name='Tipo de cliente')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre completo')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón social')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-5.', regex='^(\\d{7,8})-([\\dkK])$')], verbose_name='RUT')),
                ('business_activity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Giro comercial')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido. Ejemplo: +56912345678 o 912345678.', regex='^(\\+56)?\\s?9\\d{8}$')], verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.city')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.region')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='customers.region'),
        ),
    ]
