# Generated by Django 4.2.21 on 2025-06-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.city'),
        ),
    ]
