# Generated by Django 4.2.21 on 2025-06-03 17:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customers_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='business_activity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bussiness Activity'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Persona'), ('company', 'Empresa')], max_length=10, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido. Ejemplo: +56912345678 o 912345678.', regex='^(\\+56)?\\s?9\\d{8}$')], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-5.', regex='^(\\d{7,8})-([\\dkK])$')], verbose_name='DNI'),
        ),
    ]
