# Generated by Django 4.2.21 on 2025-06-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customers_last_name_alter_customers_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='company_name',
            new_name='company',
        ),
    ]
