# Generated by Django 4.2.21 on 2025-06-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customers_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
    ]
