# Generated by Django 4.2.21 on 2025-06-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_rename_first_name_customers_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
