# Generated by Django 4.2.21 on 2025-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customers_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
