# Generated by Django 4.2.21 on 2025-06-02 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='region',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
