# Generated by Django 4.2.21 on 2025-06-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='commune',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
    ]
